services:


  LBMExtension.locale_listener:
    class: LBM\ExtensionBundle\EventListener\LocaleListener
    arguments: ["%kernel.default_locale%"]
    tags:
        - { name: kernel.event_subscriber }

#    lbm_extension.example:
#        class: LBM\ExtensionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
