<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmBonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmBonusRepository extends \Doctrine\ORM\EntityRepository
{
}
