<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmCompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmCompetitionRepository extends \Doctrine\ORM\EntityRepository
{
}
