<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmCompetitionBonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmCompetitionBonusRepository extends \Doctrine\ORM\EntityRepository
{
}
