<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmChallengeCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmChallengeCriteriaRepository extends \Doctrine\ORM\EntityRepository
{
}
