<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmChallengeRepository extends \Doctrine\ORM\EntityRepository
{
}
