<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmCriteriaTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmCriteriaRepository extends \Doctrine\ORM\EntityRepository
{
}
