<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmEvaluationRepository extends \Doctrine\ORM\EntityRepository
{
}
