<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
