<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmSeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmSeasonRepository extends \Doctrine\ORM\EntityRepository
{
}
