<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
