<?php

namespace LBM\ChallengeBundle\Repository;

/**
 * LbmUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LbmUserRepository extends \Doctrine\ORM\EntityRepository
{
}
