<?php

namespace LBM\ExtensionBundle\Repository;

/**
 * PadarefRefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PadarefRefRepository extends \Doctrine\ORM\EntityRepository
{
}
