<?php

namespace LBM\ExtensionBundle\Repository;

/**
 * PadarefParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PadarefParentRepository extends \Doctrine\ORM\EntityRepository
{
}
